include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = K4LSnapPrefs
K4LSnapPrefs_FILES = K4LRootListController.m
K4LSnapPrefs_FRAMEWORKS = UIKit
K4LSnapPrefs_PRIVATE_FRAMEWORKS = Preferences
K4LSnapPrefs_INSTALL_PATH = /Library/PreferenceBundles
K4LSnapPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
